### ISSUE TITLE
AttributeError: '_WeakValueDictionary' object has no attribute '_addr_to_oid'

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/persistent#150]
Seen during test teardown of a large app using CPython in PURE_PYTHON=1 mode

```
From callback for ffi.gc <cdata 'struct CPersistentRingCFFI_struct *' owning 24 bytes>:
Traceback (most recent call last):
  File "//persistent/persistent/picklecache.py", line 105, in cleanup_hook
    oid = self._addr_to_oid.pop(cdata.pobj_id, None)
AttributeError: '_WeakValueDictionary' object has no attribute '_addr_to_oid'
```

This is ignored, and the dict is already gone, so there shouldn't be any harm, but it is annoying.

**Comment by jamadden** [comment]
This also shows up [testing BTrees in PURE_PYTHON mode.](https://github.com/zopefoundation/BTrees/runs/2201331904?check_suite_focus=true#step:11:7512)
```
.............From callback for ffi.gc <cdata 'struct CPersistentRingCFFI_struct *' owning 24 bytes>:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/persistent/picklecache.py", line 105, in cleanup_hook
    oid = self._addr_to_oid.pop(cdata.pobj_id, None)
AttributeError: '_WeakValueDictionary' object has no attribute '_addr_to_oid'
From callback for ffi.gc <cdata 'struct CPersistentRingCFFI_struct *' owning 24 bytes>:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/persistent/picklecache.py", line 105, in cleanup_hook
    oid = self._addr_to_oid.pop(cdata.pobj_id, None)
AttributeError: '_WeakValueDictionary' object has no attribute '_addr_to_oid'
From callback for ffi.gc <cdata 'struct CPersistentRingCFFI_struct *' owning 24 bytes>:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/persistent/picklecache.py", line 105, in cleanup_hook
    oid = self._addr_to_oid.pop(cdata.pobj_id, None)
AttributeError: '_WeakValueDictionary' object has no attribute '_addr_to_oid'
From callback for ffi.gc <cdata 'struct CPersistentRingCFFI_struct *' owning 24 bytes>:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/persistent/picklecache.py", line 105, in cleanup_hook
    oid = self._addr_to_oid.pop(cdata.pobj_id, None)
AttributeError: '_WeakValueDictionary' object has no attribute '_addr_to_oid'
......................................s...From callback for ffi.gc <cdata 'struct CPersistentRingCFFI_struct *' owning 24 bytes>:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/persistent/picklecache.py", line 105, in cleanup_hook
    oid = self._addr_to_oid.pop(cdata.pobj_id, None)
AttributeError: '_WeakValueDictionary' object has no attribute '_addr_to_oid'
```
