### ISSUE TITLE
Error: unable to execute gcc: No such file or directory

### ISSUE THREAD

**Issue by Cykooz** [zopefoundation/persistent#30]
My application is built (with zc.buildout) on a separate server with all necessary develop libraries. Then I transfer application (with all compiled eggs) to the production server where there is no developer packages (such as python-dev, gcc and other). When running application, I get an error:

```bash
unable to execute gcc: No such file or directory
Traceback (most recent call last):
  ...
  File "/home/user/myapp/src/myapp/myapp/users/resources.py", line 11, in <module>
    from persistent.persistence import Persistent
  File "/home/user/myapp/eggs/persistent-4.1.1-py2.7-linux-x86_64.egg/persistent/persistence.py", line 30, in <module>
    from . import ring
  File "/home/user/myapp/eggs/persistent-4.1.1-py2.7-linux-x86_64.egg/persistent/ring.py", line 161, in <module>
    """, include_dirs=[this_dir])
  File "/home/user/myapp/eggs/cffi-1.2.1-py2.7-linux-x86_64.egg/cffi/api.py", line 405, in verify
    lib = self.verifier.load_library()
  File "/home/user/myapp/eggs/cffi-1.2.1-py2.7-linux-x86_64.egg/cffi/verifier.py", line 100, in load_library
    self._compile_module()
  File "/home/user/myapp/eggs/cffi-1.2.1-py2.7-linux-x86_64.egg/cffi/verifier.py", line 196, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/home/user/myapp/eggs/cffi-1.2.1-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/home/user/myapp/eggs/cffi-1.2.1-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

**Comment by jamadden** [comment]
Does your application use cffi (it seems to be installed)? It's hard to use all modes of cffi without having a compiler available.

**Comment by jamadden** [comment]
Assuming you're on a typical cPython platform and are not explicitly wanting to use the (slow) pure-Python implementation for some reason, you can fix this by changing your import to use the canonical form. That is, write:
```python
from persistent import Persistent
```
instead of
```python
from persistent.persistence import Persistent
```
The latter always guarantees that you get the slow, pure-Python implementation. The former gets you the best possible implementation.

**Comment by Cykooz** [comment]
Thank you. I'll do as you suggested.
