### ISSUE TITLE
Appveyor failures for persistent 4.2.2 (test failures on 64-bit platforms)

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/persistent#51]
AFAICT the latest persistent release has no Windows wheels on PyPI because https://ci.appveyor.com/project/mgedmin/persistent/build/1.0.31 is all red.

All 64-bit tests fail with

```
======================================================================
FAIL: test_hash_equal (persistent.tests.test_timestamp.PyAndCComparisonTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\persistent\persistent\tests\test_timestamp.py", line 266, in test_hash_equal
    self.assertEqual(hash(c), hash(py))
AssertionError: -1419374591 != 1979033151
======================================================================
FAIL: test_hash_equal_constants (persistent.tests.test_timestamp.PyAndCComparisonTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\persistent\persistent\tests\test_timestamp.py", line 334, in test_hash_equal_constants
    self.assertEqual(c.__hash__(), 1000006000001)
AssertionError: -721379967 != 1000006000001L
----------------------------------------------------------------------
```
(except on Python 3 the 1st error is `AssertionError: -1419374591 != -3850693964765720575`).

I can't figure out why the 32-bit tests failed (an error from `twine upload`?).

**Comment by mgedmin** [comment]
I've triggered a rebuild of that commit, and from what I can see `twine upload` hangs for a long time after printing

```
Uploading distributions to https://pypi.python.org/pypi
```

and then (judging from the original failure log, which ends with exactly that line), exits with a non-zero status code without printing any diagnostic information.

I hate everything.
