### ISSUE TITLE
Regression: persistent 4.4.0 cannot be installed on pypy

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/persistent#88]
```
$ virtualenv -p pypy env
$ env/bin/pip install persistent==4.4.0
```

```
Building wheels for collected packages: persistent
  Running setup.py bdist_wheel for persistent ... error
  Complete output from command /tmp/env/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-JxosYs/persistent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-pRuF5D --python-tag pp2510:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/persistent
  copying persistent/__init__.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/interfaces.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/list.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/_compat.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/wref.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/picklecache.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/timestamp.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/persistence.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/ring.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/dict.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/_ring_build.py -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/mapping.py -> build/lib.linux-x86_64-2.7/persistent
  creating build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/__init__.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/test_wref.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/test_mapping.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/test_ring.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/test_docs.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/utils.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/attrhooks.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/test_timestamp.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/test_picklecache.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/test_list.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/test_persistence.py -> build/lib.linux-x86_64-2.7/persistent/tests
  copying persistent/tests/cucumbers.py -> build/lib.linux-x86_64-2.7/persistent/tests
  running egg_info
  writing persistent.egg-info/PKG-INFO
  writing dependency_links to persistent.egg-info/dependency_links.txt
  writing requirements to persistent.egg-info/requires.txt
  writing top-level names to persistent.egg-info/top_level.txt
  reading manifest file 'persistent.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.dll' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyo' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
  no previously-included directories found matching 'docs/_build'
  no previously-included directories found matching 'persistent/__pycache__'
  writing manifest file 'persistent.egg-info/SOURCES.txt'
  copying persistent/_compat.h -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/_timestamp.c -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/cPersistence.c -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/cPersistence.h -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/cPickleCache.c -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/ring.c -> build/lib.linux-x86_64-2.7/persistent
  copying persistent/ring.h -> build/lib.linux-x86_64-2.7/persistent
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-2.7/persistent._ring.c'
  creating build/temp.linux-x86_64-2.7
  building 'persistent._ring' extension
  creating build/temp.linux-x86_64-2.7/build
  creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
  cc -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-install-JxosYs/persistent/persistent -I/tmp/env/include -c build/temp.linux-x86_64-2.7/persistent._ring.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/persistent._ring.o
  cc -pthread -shared build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/persistent._ring.o -o build/lib.linux-x86_64-2.7/persistent/_ring.pypy-41-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/_ring.pypy-41-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/cPickleCache.c -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/cPersistence.h -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/__init__.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/interfaces.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/list.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/_compat.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/cPersistence.c -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/wref.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/picklecache.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/_timestamp.c -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/ring.c -> build/bdist.linux-x86_64/wheel/persistent
  creating build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/__init__.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/test_wref.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/test_mapping.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/test_ring.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/test_docs.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/utils.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/attrhooks.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/test_timestamp.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/test_picklecache.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/test_list.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/test_persistence.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/tests/cucumbers.py -> build/bdist.linux-x86_64/wheel/persistent/tests
  copying build/lib.linux-x86_64-2.7/persistent/_compat.h -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/timestamp.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/persistence.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/ring.h -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/ring.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/dict.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/_ring_build.py -> build/bdist.linux-x86_64/wheel/persistent
  copying build/lib.linux-x86_64-2.7/persistent/mapping.py -> build/bdist.linux-x86_64/wheel/persistent
  running install_headers
  creating build/bdist.linux-x86_64/wheel/persistent-4.4.0.data
  creating build/bdist.linux-x86_64/wheel/persistent-4.4.0.data/headers
  Traceback (most recent call last):
    File "<module>", line 1, in <module>
    File "/tmp/pip-install-JxosYs/persistent/setup.py", line 130, in <module>
      entry_points={},
    File "/tmp/env/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/pypy/lib-python/2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/env/site-packages/wheel/bdist_wheel.py", line 238, in run
      self.run_command('install')
    File "/usr/lib/pypy/lib-python/2.7/distutils/cmd.py", line 334, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/env/site-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/usr/lib/pypy/lib-python/2.7/distutils/command/install.py", line 625, in run
      self.run_command(cmd_name)
    File "/usr/lib/pypy/lib-python/2.7/distutils/cmd.py", line 334, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/pypy/lib-python/2.7/distutils/command/install_headers.py", line 42, in run
      (out, _) = self.copy_file(header, self.install_dir)
    File "/usr/lib/pypy/lib-python/2.7/distutils/cmd.py", line 373, in copy_file
      dry_run=self.dry_run)
    File "/usr/lib/pypy/lib-python/2.7/distutils/file_util.py", line 108, in copy_file
      if not os.path.isfile(src):
    File "/tmp/env/lib-python/2.7/genericpath.py", line 37, in isfile
      st = os.stat(path)
  TypeError: expected string, got instance object
  
  ----------------------------------------
  Failed building wheel for persistent
  Running setup.py clean for persistent
Failed to build persistent
Installing collected packages: zope.interface, persistent
  Running setup.py install for persistent ... error
    Complete output from command /tmp/env/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-JxosYs/persistent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0vS2xa/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/env/include/site/python2.7/persistent:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/persistent
    copying persistent/__init__.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/interfaces.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/list.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/_compat.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/wref.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/picklecache.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/timestamp.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/persistence.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/ring.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/dict.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/_ring_build.py -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/mapping.py -> build/lib.linux-x86_64-2.7/persistent
    creating build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/__init__.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/test_wref.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/test_mapping.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/test_ring.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/test_docs.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/utils.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/attrhooks.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/test_timestamp.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/test_picklecache.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/test_list.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/test_persistence.py -> build/lib.linux-x86_64-2.7/persistent/tests
    copying persistent/tests/cucumbers.py -> build/lib.linux-x86_64-2.7/persistent/tests
    running egg_info
    writing persistent.egg-info/PKG-INFO
    writing dependency_links to persistent.egg-info/dependency_links.txt
    writing requirements to persistent.egg-info/requires.txt
    writing top-level names to persistent.egg-info/top_level.txt
    reading manifest file 'persistent.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'persistent/__pycache__'
    writing manifest file 'persistent.egg-info/SOURCES.txt'
    copying persistent/_compat.h -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/_timestamp.c -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/cPersistence.c -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/cPersistence.h -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/cPickleCache.c -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/ring.c -> build/lib.linux-x86_64-2.7/persistent
    copying persistent/ring.h -> build/lib.linux-x86_64-2.7/persistent
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/persistent._ring.c'
    creating build/temp.linux-x86_64-2.7
    building 'persistent._ring' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    cc -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-install-JxosYs/persistent/persistent -I/tmp/env/include -c build/temp.linux-x86_64-2.7/persistent._ring.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/persistent._ring.o
    cc -pthread -shared build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/persistent._ring.o -o build/lib.linux-x86_64-2.7/persistent/_ring.pypy-41-x86_64-linux-gnu.so
    running install_lib
    creating /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/_ring.pypy-41-x86_64-linux-gnu.so -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/cPickleCache.c -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/cPersistence.h -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/__init__.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/interfaces.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/list.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/_compat.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/cPersistence.c -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/wref.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/picklecache.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/_timestamp.c -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/ring.c -> /tmp/env/site-packages/persistent
    creating /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/__init__.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/test_wref.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/test_mapping.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/test_ring.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/test_docs.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/utils.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/attrhooks.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/test_timestamp.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/test_picklecache.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/test_list.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/test_persistence.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/tests/cucumbers.py -> /tmp/env/site-packages/persistent/tests
    copying build/lib.linux-x86_64-2.7/persistent/_compat.h -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/timestamp.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/persistence.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/ring.h -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/ring.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/dict.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/_ring_build.py -> /tmp/env/site-packages/persistent
    copying build/lib.linux-x86_64-2.7/persistent/mapping.py -> /tmp/env/site-packages/persistent
    byte-compiling /tmp/env/site-packages/persistent/__init__.py to __init__.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/interfaces.py to interfaces.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/list.py to list.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/_compat.py to _compat.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/wref.py to wref.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/picklecache.py to picklecache.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/__init__.py to __init__.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/test_wref.py to test_wref.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/test_mapping.py to test_mapping.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/test_ring.py to test_ring.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/test_docs.py to test_docs.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/utils.py to utils.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/attrhooks.py to attrhooks.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/test_timestamp.py to test_timestamp.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/test_picklecache.py to test_picklecache.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/test_list.py to test_list.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/test_persistence.py to test_persistence.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/tests/cucumbers.py to cucumbers.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/timestamp.py to timestamp.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/persistence.py to persistence.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/ring.py to ring.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/dict.py to dict.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/_ring_build.py to _ring_build.pypy-41.pyc
    byte-compiling /tmp/env/site-packages/persistent/mapping.py to mapping.pypy-41.pyc
    running install_headers
    creating /tmp/env/include/site
    error: could not create '/tmp/env/include/site': Permission denied
    
    ----------------------------------------
Command "/tmp/env/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-JxosYs/persistent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0vS2xa/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/env/include/site/python2.7/persistent" failed with error code 1 in /tmp/pip-install-JxosYs/persistent/

```

`pip install persistent=4.3.0` succeeds.

`pypy --version` prints

```
Python 2.7.13 (5.10.0+dfsg-3build2, Feb 06 2018, 18:37:50)
[PyPy 5.10.0 with GCC 7.3.0]
```

I'm on Ubuntu 18.04 LTS.  I see a similar problem with pypy3 (PyPy 5.9.0-beta0).

**Comment by jamadden** [comment]
Yup, I've observed that too. I debugged some, but couldn't find what we're doing wrong, so I opened [a CFFI issue](https://bitbucket.org/cffi/cffi/issues/377/typeerror-expected-string-got-instance) for help.

**Comment by mgedmin** [comment]
For the record, `/tmp/env/include` is a symlink to `/usr/lib/pypy/include`, so it's not surprising `setup.py install` fails with a permission error.  My virtualenv version is 16.0.0, and env/bin/pip --version says 18.0.

**Comment by jamadden** [comment]
This is our fault. [setup.py does this](https://github.com/zopefoundation/persistent/blob/master/setup.py#L41):
```python
if is_pypy or is_jython:
    ext_modules = headers = []
```

The CFFI code at some point does `dist.ext_modules.append(ext)`. When `ext_modules` and `headers` are the same object...we try to install the extension as a header, which is clearly not what we want.

**Comment by jamadden** [comment]
I'm working on a PR.
